ingress-nginx:
  controller:
    nodeSelector:
      node-type: control-plane

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
    
    ingressClassResource:
      enabled: true
      name: nginx

    service:
      type: LoadBalancer
