# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd
#   namespace: {{ $.Values.default.namespace }}
# spec:
#   project: argocd
#   source:
#     repoURL: {{ $.Values.default.repoURL }}
#     targetRevision: HEAD  
#     path: argo-cd/argo-cd
#     helm:
#       valuesFiles:
#       - values.yaml
#   destination:
#     server: {{ $.Values.default.server }}
#     namespace: {{ $.Values.default.namespace }}
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true

{{- $pathRoot := .Values.projects.argocd.pathRoot -}}
{{- $project := .Values.projects.argocd.project -}}
{{- $repoURL := .Values.projects.argocd.repoURL -}}
{{- $targetRevision := .Values.projects.argocd.targetRevision -}}
{{- $valuesFiles := .Values.projects.argocd.valuesFiles -}}

{{- range .Values.projects.argocd.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.default.manifest.namespace }}
spec:
  project: {{ $project }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}  
    path: {{ $pathRoot }}
    helm:
      valuesFiles: {{ $valuesFiles }}
  destination:
    server: {{ $.Values.default.manifest.server }}
    namespace: {{ .namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}