apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    repoURL: {{ $.Values.applicationSetConfig.repoURL }}
    targetRevision: HEAD
    path: argocd  
    helm:
      valuesFiles: 
        - values.yaml 
  destination:
    server: {{ $.Values.applicationSetConfig.server }}
    namespace: {{ $.Values.applicationSetConfig.namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
