default:
  manifest:
    namespace: argocd
    server: https://kubernetes.default.svc

projects:
  argocd:
    project: argocd
    pathRoot: argo-cd/argo-cd
    repoURL: https://github.com/DiegoFr75/kubernetes-config.git
    targetRevision: HEAD
    valuesFile: 
    - values.yaml

    applications:
    - name: argocd
      namespace: argocd

  monitoring:
    project: monitoring
    pathRoot: monitoring
    repoURL: https://github.com/DiegoFr75/kubernetes-config.git
    targetRevision: HEAD
    valuesFile: 
    - values.yaml

    applications:
    - name: grafana
      namespace: grafana