applicationSetConfig:
  server: https://kubernetes.default.svc
  repoURL: https://github.com/DiegoFr75/kubernetes-config.git
  namespace: argocd

argo-cd:
  nameOverride: argocd
  fullnameOverride: "argocd"

  global:
    logging:
      format: json
      level: info

  controller:
    name: application-controller
    replicas: 1

    resources: {}
    #  limits:
    #    cpu: 500m
    #    memory: 512Mi
    #  requests:
    #    cpu: 250m
    #    memory: 256Mi

  ## Dex
  dex:
    enabled: true
    name: dex-server
    resources: {}
    #  limits:
    #    cpu: 50m
    #    memory: 64Mi
    #  requests:
    #    cpu: 10m
    #    memory: 32Mi

  redis:
    enabled: true
    name: redis
    resources: {}
    #  limits:
    #    cpu: 200m
    #    memory: 128Mi
    #  requests:
    #    cpu: 100m
    #    memory: 64Mi

  notifications:
    enabled: false
    
  redis-ha:
    enabled: false

  ## Server
  server:
    name: server
    replicas: 1
    resources: {}
    #  limits:
    #    cpu: 100m
    #    memory: 128Mi
    #  requests:
    #    cpu: 50m
    #    memory: 64Mi

    ## Server service configuration
    service:
      type: ClusterIP
      
    # Argo CD server ingress configuration
    ingress:
      enabled: false
      # -- Defines which ingress controller will implement the resource
      ingressClassName: ""
      # -- Argo CD server hostname
      # @default -- `""` (defaults to global.domain)
      hostname: ""
      # -- The path to Argo CD server
      path: /
      # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
      pathType: Prefix
      # -- Enable TLS configuration for the hostname defined at `server.ingress.hostname`
      ## TLS certificate will be retrieved from a TLS secret `argocd-server-tls`
      ## You can create this secret via `certificate` or `certificateSecret` option
      tls: false

    ingressGrpc:
      # -- Enable an ingress resource for the Argo CD server for dedicated [gRPC-ingress]
      enabled: false

  ## Repo Server
  repoServer:
    name: repo-server
    replicas: 1
    # -- Resource limits and requests for the repo server pods
    resources: {}
    #  limits:
    #    cpu: 50m
    #    memory: 128Mi
    #  requests:
    #    cpu: 10m
    #    memory: 64Mi
