apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $.Values.appOfApps.projectName }}
  namespace: {{ $.Values.default.namespace }}
spec:
  sourceRepos:
  - {{ $.Values.default.repoURL }}
  destinations:
  - namespace: {{ $.Values.appOfApps.namespace }}
    server: {{ $.Values.default.server }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'