{{- range $.Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ . }}
  namespace: {{ $.Values.default.manifest.namespace }}
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: {{ $.Values.default.manifest.server }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
{{- end }}