{{- $repoURL := .Values.default.manifest.repoURL -}}
{{- $project := .Values.projectApps.monitoring.projectName -}}
{{- $targetRevision := .Values.projectApps.monitoring.targetRevision -}}
{{- $valuesFiles := .Values.projectApps.monitoring.valuesFiles -}}

{{- range $.Values.projectApps.monitoring.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.default.manifest.namespace }}
spec:
  project: {{ $project }}
  source:
    repoURL: {{ $repoURL }}
    targetRevision: {{ $targetRevision }}  
    path: {{ printf "%s/%s/%s/%s" "apps-charts" $project .namespace .name }}
    helm:
      valueFiles: {{ $valuesFiles }}
  destination:
    server: {{ $.Values.default.manifest.server }}
    namespace: {{ .namespace }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}